version: "3.9"

services:
    siom:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: siom
        volumes:
            - ./:/code
        ports:
            - 8000:8000
        stdin_open: true
        tty: true
        networks:
            - local-network

networks:
  local-network:
    name: local-network
    external: true
