# Generated by Django 3.2.25 on 2024-05-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('broken_cable', 'Cabo Rompido'), ('fallen_tree', 'Árvore Caída/Poda'), ('rubble', 'Entulho'), ('public_lighting', 'Iluminação Pública'), ('asphalt', 'Asfalto'), ('flooding', 'Alagamento'), ('high_grass', 'Mato Alto'), ('zoonoses', 'Zoonoses'), ('robbery', 'Assalto/Roubo'), ('sewer', 'Esgoto'), ('loud_noise', 'Som Alto'), ('illegal_fire', 'Incêndio Clandestino')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='occurrences/')),
            ],
        ),
    ]
