# Generated by Django 3.2.25 on 2024-05-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='reported_by',
            field=models.CharField(default='Anônimo', max_length=100),
        ),
    ]
