# Generated by Django 3.2.25 on 2024-05-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0002_alter_occurrence_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
